

# =========================
# INSTALL MONGODB
# =========================
- name: Install MongoDB via Helm
  command: >
    helm install --install mongodb {{ role_path }}/../helm_charts/mongodb
    --namespace db
    --create-namespace
  register: helm_install_result

- name: Wait for MongoDB pods to be ready
  command: kubectl rollout status deployment/mongodb -n db
  register: rollout_status
  changed_when: false