---
task_state: present

# Network Configuration
private_subnet_ids: []

# EKS Cluster Configuration
eks_cluster_version: "1.29"

# Node Group Configuration
eks_node_group_desired_size: 1
eks_node_group_min_size: 1
eks_node_group_max_size: 2
eks_node_instance_types:
  - t3.medium