- name: Delete EKS Stack
  hosts: local
  gather_facts: false
  roles:
    - eks
  vars:
    task_state: absent
  environment: "{{ environment_vars }}"

- name: Delete VPC Stack
  hosts: local
  gather_facts: false
  roles:
    - vpc
  vars:
    task_state: absent
  environment: "{{ environment_vars }}"